apiVersion: v1
kind: Service
metadata:
  name: coronaweb-spring
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: coronaweb-spring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coronaweb-spring
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  selector:
    matchLabels:
      app: coronaweb-spring
  template:
    metadata:
      labels:
        app: coronaweb-spring
    spec:
      containers:
        - name: coronaweb-spring
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8081